//! ADR-103 A7 / P2 package D: `rule_hash` on chain events and the chain
//! subscription (replay + live).

#![cfg(all(feature = "native", feature = "exochain"))]

use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, Instant};

use clawft_kernel::chain::ChainManager;
use clawft_kernel::chain_rule_hash::RuleHashCell;
use clawft_kernel::chain_subscribe::{ChainFilter, ChainItem, SubscribeError};

fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/chain_pre_p2.jsonl")
}

fn with_rules(byte: u8) -> ChainManager {
    let cm = ChainManager::new(0, 0);
    cm.set_rule_hash_provider(Arc::new(move || Some([byte; 32])));
    cm
}

// ---- golden: pre-P2 events hash exactly as before ----

/// The fixture was generated by an independent implementation of the
/// pre-P2 algorithm (SHAKE-256 over seq, chain_id, prev, source, 0, kind,
/// 0, ts, payload_hash), not by this crate.
#[test]
fn pre_p2_fixture_verifies_and_carries_no_rule_hash() {
    let cm = ChainManager::load_from_file(&fixture(), 0).expect("pre-P2 chain must verify");
    assert!(cm.verify_integrity().valid);
    let events = cm.tail(0);
    assert_eq!(events.len(), 5);
    assert!(events.iter().all(|e| e.rule_hash.is_none()));
}

#[test]
fn pre_p2_fixture_unchanged_by_save_and_reload() {
    let cm = ChainManager::load_from_file(&fixture(), 0).unwrap();
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    // No rule_hash key is emitted for events without one.
    assert!(!std::fs::read_to_string(&p).unwrap().contains("rule_hash"));
    let again = ChainManager::load_from_file(&p, 0).unwrap();
    let (a, b) = (cm.tail(0), again.tail(0));
    assert_eq!(a.len(), b.len());
    assert!(a.iter().zip(&b).all(|(x, y)| x.hash == y.hash));
}

#[test]
fn appending_without_a_provider_matches_the_old_hash_input() {
    // Extend the fixture chain; the new event links to the golden tip and
    // the whole chain still verifies.
    let cm = ChainManager::load_from_file(&fixture(), 0).unwrap();
    let ev = cm.append("kernel", "later", None);
    assert!(ev.rule_hash.is_none());
    assert!(cm.verify_integrity().valid);
}

// ---- rule_hash is committed to by the hash ----

#[test]
fn provider_stamps_every_append_and_changes_the_hash() {
    let plain = ChainManager::new(0, 0);
    let stamped = with_rules(7);
    let e = stamped.append("s", "k", None);
    assert_eq!(e.rule_hash, Some([7u8; 32]));
    assert!(stamped.verify_integrity().valid);
    // Same position and fields, different commitment than an unstamped event.
    let p = plain.append("s", "k", None);
    assert!(p.rule_hash.is_none());
    assert_ne!(p.hash, e.hash);
}

#[test]
fn flipping_one_rule_hash_byte_fails_verification() {
    let cm = with_rules(9);
    cm.append("s", "k", Some(serde_json::json!({"a": 1})));
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    assert!(ChainManager::load_from_file(&p, 0).is_ok());

    let text = std::fs::read_to_string(&p).unwrap();
    let needle = format!("\"rule_hash\":[9,{}", vec!["9"; 31].join(","));
    assert!(text.contains(&needle), "rule_hash serialized: {text}");
    let tampered = text.replacen(&needle, &needle.replacen("[9,", "[8,", 1), 1);
    std::fs::write(&p, tampered).unwrap();
    let err = ChainManager::load_from_file(&p, 0).unwrap_err().to_string();
    assert!(err.contains("integrity"), "{err}");
}

#[test]
fn stripping_rule_hash_fails_verification_like_an_old_binary() {
    // An old binary ignores the unknown field, recomputes without it and
    // must fail loudly. Simulate by removing the key before loading.
    // `with_rules` installs the provider AFTER the genesis event, so only
    // events appended below are stamped; genesis carries no rule_hash.
    let cm = with_rules(5);
    cm.append("s", "k", Some(serde_json::json!({"a": 1})));
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    let saved = std::fs::read_to_string(&p).unwrap();
    assert!(saved.contains("\"rule_hash\""), "stamped event must be saved with rule_hash");
    let mut lines = Vec::new();
    for l in std::fs::read_to_string(&p).unwrap().lines() {
        let mut v: serde_json::Value = serde_json::from_str(l).unwrap();
        v.as_object_mut().unwrap().remove("rule_hash");
        lines.push(v.to_string());
    }
    std::fs::write(&p, lines.join("\n") + "\n").unwrap();
    assert!(ChainManager::load_from_file(&p, 0).is_err());
}

/// Load verifies stored hashes (it does not recompute-and-overwrite): an
/// edited payload byte fails the load.
#[test]
fn an_edited_payload_fails_load() {
    let cm = ChainManager::new(0, 0);
    cm.append("s", "k", Some(serde_json::json!({"note": "aaaa"})));
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    assert!(ChainManager::load_from_file(&p, 0).is_ok());
    let text = std::fs::read_to_string(&p).unwrap();
    assert!(text.contains("aaaa"));
    std::fs::write(&p, text.replacen("aaaa", "aaab", 1)).unwrap();
    let err = ChainManager::load_from_file(&p, 0).unwrap_err().to_string();
    assert!(err.contains("integrity"), "{err}");
}

#[test]
fn rule_hash_round_trips_through_json_and_rvf() {
    let cm = with_rules(3);
    cm.append("s", "k", Some(serde_json::json!({"x": true})));
    let dir = tempfile::tempdir().unwrap();

    let j = dir.path().join("c.jsonl");
    cm.save_to_file(&j).unwrap();
    let from_json = ChainManager::load_from_file(&j, 0).unwrap();

    let r = dir.path().join("c.rvf");
    cm.save_to_rvf(&r).unwrap();
    let from_rvf = ChainManager::load_from_rvf(&r, 0).unwrap();

    for restored in [from_json, from_rvf] {
        assert!(restored.verify_integrity().valid);
        let (a, b) = (cm.tail(0), restored.tail(0));
        assert_eq!(a.len(), b.len());
        for (x, y) in a.iter().zip(&b) {
            assert_eq!(x.rule_hash, y.rule_hash);
            assert_eq!(x.hash, y.hash);
        }
    }
}

#[tokio::test]
async fn append_signed_accepts_a_stamped_event_and_rejects_a_stripped_one() {
    let src = with_rules(4);
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    src.save_to_file(&p).unwrap();
    let dst = Arc::new(ChainManager::load_from_file(&p, 0).unwrap());

    let ev = src.append("s", "k", None);
    let mut stripped = ev.clone();
    stripped.rule_hash = None;
    assert!(dst.append_signed(stripped).is_err());

    let mut sub = dst.subscribe(ChainFilter::default()).unwrap();
    dst.append_signed(ev.clone()).unwrap();
    match sub.next().await.unwrap() {
        ChainItem::Event(e) => assert_eq!(e.rule_hash, Some([4u8; 32])),
        other => panic!("{other:?}"),
    }
    assert!(dst.verify_integrity().valid);
}

// ---- subscribe ----

async fn collect_until(
    sub: &mut clawft_kernel::chain_subscribe::ChainSubscription,
    last_seq: u64,
) -> Vec<u64> {
    let mut seen = Vec::new();
    while let Some(item) = tokio::time::timeout(Duration::from_secs(10), sub.next())
        .await
        .expect("subscription stalled")
    {
        match item {
            ChainItem::Event(e) => {
                seen.push(e.sequence);
                if e.sequence >= last_seq {
                    break;
                }
            }
            ChainItem::Lagged { missed, .. } => panic!("unexpected lag of {missed}"),
        }
    }
    seen
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn replay_then_live_has_no_gap_and_no_duplicate_100_iterations() {
    const APPENDS: u64 = 60;
    for iter in 0..100u64 {
        let cm = Arc::new(ChainManager::new(0, 0));
        let writer = {
            let cm = Arc::clone(&cm);
            std::thread::spawn(move || {
                for i in 0..APPENDS {
                    cm.append("w", "race.tick", Some(serde_json::json!({ "i": i })));
                    if i % 7 == 0 {
                        std::thread::yield_now();
                    }
                }
            })
        };
        // Subscribe at a varying point while the writer runs.
        for _ in 0..(iter % 13) {
            tokio::task::yield_now().await;
        }
        let mut sub = cm
            .subscribe(ChainFilter {
                kind_prefix: None,
                from_seq: Some(0),
            })
            .unwrap();
        let seen = collect_until(&mut sub, APPENDS).await; // genesis is seq 0
        writer.join().unwrap();
        let expect: Vec<u64> = (0..=APPENDS).collect();
        assert_eq!(seen, expect, "iteration {iter}");
    }
}

#[tokio::test]
async fn kind_prefix_filters_replay_and_live() {
    let cm = Arc::new(ChainManager::new(0, 0));
    cm.append("s", "a.one", None);
    cm.append("s", "b.one", None);
    let mut sub = cm
        .subscribe(ChainFilter {
            kind_prefix: Some("a.".into()),
            from_seq: Some(0),
        })
        .unwrap();
    cm.append("s", "b.two", None);
    cm.append("s", "a.two", None);
    let mut kinds = Vec::new();
    for _ in 0..2 {
        match sub.next().await.unwrap() {
            ChainItem::Event(e) => kinds.push(e.kind),
            ChainItem::Lagged { missed, .. } => panic!("lag {missed}"),
        }
    }
    assert_eq!(kinds, ["a.one", "a.two"]);
}

#[tokio::test]
async fn live_only_skips_history() {
    let cm = Arc::new(ChainManager::new(0, 0));
    cm.append("s", "old", None);
    let mut sub = cm.subscribe(ChainFilter::default()).unwrap();
    cm.append("s", "new", None);
    match sub.next().await.unwrap() {
        ChainItem::Event(e) => assert_eq!(e.kind, "new"),
        other => panic!("{other:?}"),
    }
}

#[tokio::test]
async fn a_stalled_subscriber_never_slows_append_and_sees_lagged() {
    let cm = Arc::new(ChainManager::new(0, 0));
    let mut stalled = cm.subscribe(ChainFilter::default()).unwrap();
    let started = Instant::now();
    for i in 0..5000u64 {
        cm.append("s", "flood", Some(serde_json::json!({ "i": i })));
    }
    assert!(
        started.elapsed() < Duration::from_secs(20),
        "append blocked by a stalled subscriber: {:?}",
        started.elapsed()
    );
    match stalled.next().await.unwrap() {
        ChainItem::Lagged { missed, .. } => assert!(missed > 0),
        other => panic!("expected Lagged, got {other:?}"),
    }
    // It then recovers and keeps receiving.
    assert!(matches!(stalled.next().await, Some(ChainItem::Event(_))));
}

#[tokio::test]
async fn lagged_then_resubscribe_from_resume_from_recovers_everything() {
    let cm = Arc::new(ChainManager::new(0, 0));
    let mut sub = cm.subscribe(ChainFilter::default()).unwrap();
    // One delivered event, then a flood past the buffer.
    cm.append("s", "k", None); // seq 1
    let first = match sub.next().await.unwrap() {
        ChainItem::Event(e) => e.sequence,
        other => panic!("{other:?}"),
    };
    assert_eq!(first, 1);
    for _ in 0..3000 {
        cm.append("s", "k", None);
    }
    let resume = match sub.next().await.unwrap() {
        ChainItem::Lagged { missed, resume_from } => {
            assert!(missed > 0);
            resume_from
        }
        other => panic!("expected Lagged, got {other:?}"),
    };
    assert_eq!(resume, first + 1);
    // Resubscribe: replay from resume_from reaches the head contiguously.
    let head = cm.head_sequence();
    let mut again = cm
        .subscribe(ChainFilter {
            kind_prefix: None,
            from_seq: Some(resume),
        })
        .unwrap();
    let seen = collect_until(&mut again, head).await;
    assert_eq!(seen, (resume..=head).collect::<Vec<_>>());
}

#[tokio::test]
async fn kind_prefix_and_lagged_compose() {
    let cm = Arc::new(ChainManager::new(0, 0));
    let mut sub = cm
        .subscribe(ChainFilter {
            kind_prefix: Some("keep.".into()),
            from_seq: None,
        })
        .unwrap();
    for i in 0..3000 {
        cm.append("s", if i % 2 == 0 { "keep.x" } else { "drop.x" }, None);
    }
    assert!(matches!(
        sub.next().await.unwrap(),
        ChainItem::Lagged { missed, .. } if missed > 0
    ));
    // After the lag only matching events are delivered.
    for _ in 0..50 {
        match sub.next().await.unwrap() {
            ChainItem::Event(e) => assert!(e.kind.starts_with("keep.")),
            other => panic!("{other:?}"),
        }
    }
}

#[tokio::test]
async fn subscription_ends_when_the_manager_drops() {
    let cm = Arc::new(ChainManager::new(0, 0));
    let mut sub = cm.subscribe(ChainFilter::default()).unwrap();
    drop(cm);
    let end = tokio::time::timeout(Duration::from_secs(5), sub.next())
        .await
        .expect("subscription must end, not hang");
    assert!(end.is_none());
}

#[tokio::test]
async fn deep_replay_is_paged_and_complete() {
    let cm = Arc::new(ChainManager::new(0, 0));
    for _ in 0..5000 {
        cm.append("s", "k", None);
    }
    let head = cm.head_sequence();
    let mut sub = cm
        .subscribe(ChainFilter {
            kind_prefix: Some("k".into()),
            from_seq: Some(0),
        })
        .unwrap();
    // Appends continue between pages without stalling or duplicating.
    let first = match sub.next().await.unwrap() {
        ChainItem::Event(e) => e.sequence,
        other => panic!("{other:?}"),
    };
    assert_eq!(first, 1); // genesis (seq 0) has kind "genesis"
    cm.append("s", "k", None);
    let rest = collect_until(&mut sub, head + 1).await;
    assert_eq!(rest, (2..=head + 1).collect::<Vec<_>>());
}

#[test]
fn replay_window_is_enforced_with_a_typed_error() {
    let cm = Arc::new(ChainManager::new(0, 0));
    for _ in 0..50 {
        cm.append("s", "k", None);
    }
    cm.set_max_replay_window(10);
    let err = cm
        .subscribe(ChainFilter {
            kind_prefix: None,
            from_seq: Some(0),
        })
        .unwrap_err();
    assert_eq!(
        err,
        SubscribeError::ReplayWindowExceeded {
            requested: 0,
            oldest_allowed: 41
        }
    );
    assert!(
        cm.subscribe(ChainFilter {
            kind_prefix: None,
            from_seq: Some(41)
        })
        .is_ok()
    );
}

// ---- rule_hash provider containment ----

#[test]
fn a_panicking_provider_does_not_poison_the_chain() {
    let cm = ChainManager::new(0, 0);
    cm.set_rule_hash_provider(Arc::new(|| panic!("provider bug")));
    let e = cm.append("s", "k", None);
    assert!(e.rule_hash.is_none());
    // The chain is still usable and consistent.
    cm.append("s", "k2", None);
    assert!(cm.verify_integrity().valid);
}

/// The documented contract: a provider reads lock-free state. A provider
/// built on `RuleHashCell` is unaffected by an unrelated write-held lock,
/// and one using `try_read` degrades instead of deadlocking.
#[test]
fn provider_with_a_write_held_lock_does_not_deadlock_append() {
    let rules = Arc::new(std::sync::RwLock::new(Some([6u8; 32])));
    let cm = Arc::new(ChainManager::new(0, 0));
    let r = Arc::clone(&rules);
    cm.set_rule_hash_provider(Arc::new(move || r.try_read().ok().and_then(|g| *g)));

    let (held_tx, held_rx) = std::sync::mpsc::channel();
    let t = {
        let (cm, rules) = (Arc::clone(&cm), Arc::clone(&rules));
        std::thread::spawn(move || {
            let _w = rules.write().unwrap(); // write-held across the append
            held_tx.send(()).unwrap();
            cm.append("s", "while-write-held", None)
        })
    };
    held_rx.recv().unwrap();
    let e = t.join().expect("append must not deadlock");
    assert!(e.rule_hash.is_none(), "try_read miss degrades to None");
    assert!(cm.append("s", "after", None).rule_hash.is_some());
}

#[test]
fn rule_hash_cell_provider_stamps_without_locking() {
    let cell = Arc::new(RuleHashCell::new());
    let cm = ChainManager::new(0, 0);
    cm.set_rule_hash_provider(cell.provider());
    assert!(cm.append("s", "a", None).rule_hash.is_none());
    cell.set(Some([1; 32]));
    assert_eq!(cm.append("s", "b", None).rule_hash, Some([1; 32]));
    cell.set(Some([2; 32]));
    assert_eq!(cm.append("s", "c", None).rule_hash, Some([2; 32]));
    assert!(cm.verify_integrity().valid);
}
