//! ADR-103 A7 / P2 package D: `rule_hash` on chain events and the chain
//! subscription (replay + live).

#![cfg(all(feature = "native", feature = "exochain"))]

use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, Instant};

use clawft_kernel::chain::ChainManager;
use clawft_kernel::chain_subscribe::{ChainFilter, ChainItem};

fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/chain_pre_p2.jsonl")
}

fn with_rules(byte: u8) -> ChainManager {
    let cm = ChainManager::new(0, 0);
    cm.set_rule_hash_provider(Arc::new(move || Some([byte; 32])));
    cm
}

// ---- golden: pre-P2 events hash exactly as before ----

/// The fixture was generated by an independent implementation of the
/// pre-P2 algorithm (SHAKE-256 over seq, chain_id, prev, source, 0, kind,
/// 0, ts, payload_hash), not by this crate.
#[test]
fn pre_p2_fixture_verifies_and_carries_no_rule_hash() {
    let cm = ChainManager::load_from_file(&fixture(), 0).expect("pre-P2 chain must verify");
    assert!(cm.verify_integrity().valid);
    let events = cm.tail(0);
    assert_eq!(events.len(), 5);
    assert!(events.iter().all(|e| e.rule_hash.is_none()));
}

#[test]
fn pre_p2_fixture_unchanged_by_save_and_reload() {
    let cm = ChainManager::load_from_file(&fixture(), 0).unwrap();
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    // No rule_hash key is emitted for events without one.
    assert!(!std::fs::read_to_string(&p).unwrap().contains("rule_hash"));
    let again = ChainManager::load_from_file(&p, 0).unwrap();
    let (a, b) = (cm.tail(0), again.tail(0));
    assert_eq!(a.len(), b.len());
    assert!(a.iter().zip(&b).all(|(x, y)| x.hash == y.hash));
}

#[test]
fn appending_without_a_provider_matches_the_old_hash_input() {
    // Extend the fixture chain; the new event links to the golden tip and
    // the whole chain still verifies.
    let cm = ChainManager::load_from_file(&fixture(), 0).unwrap();
    let ev = cm.append("kernel", "later", None);
    assert!(ev.rule_hash.is_none());
    assert!(cm.verify_integrity().valid);
}

// ---- rule_hash is committed to by the hash ----

#[test]
fn provider_stamps_every_append_and_changes_the_hash() {
    let plain = ChainManager::new(0, 0);
    let stamped = with_rules(7);
    let e = stamped.append("s", "k", None);
    assert_eq!(e.rule_hash, Some([7u8; 32]));
    assert!(stamped.verify_integrity().valid);
    // Same position and fields, different commitment than an unstamped event.
    let p = plain.append("s", "k", None);
    assert!(p.rule_hash.is_none());
    assert_ne!(p.hash, e.hash);
}

#[test]
fn flipping_one_rule_hash_byte_fails_verification() {
    let cm = with_rules(9);
    cm.append("s", "k", Some(serde_json::json!({"a": 1})));
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    assert!(ChainManager::load_from_file(&p, 0).is_ok());

    let text = std::fs::read_to_string(&p).unwrap();
    let needle = format!("\"rule_hash\":[9,{}", vec!["9"; 31].join(","));
    assert!(text.contains(&needle), "rule_hash serialized: {text}");
    let tampered = text.replacen(&needle, &needle.replacen("[9,", "[8,", 1), 1);
    std::fs::write(&p, tampered).unwrap();
    let err = ChainManager::load_from_file(&p, 0).unwrap_err().to_string();
    assert!(err.contains("integrity"), "{err}");
}

#[test]
fn stripping_rule_hash_fails_verification_like_an_old_binary() {
    // An old binary ignores the unknown field, recomputes without it and
    // must fail loudly. Simulate by removing the key before loading.
    let cm = with_rules(5);
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    cm.save_to_file(&p).unwrap();
    let mut lines = Vec::new();
    for l in std::fs::read_to_string(&p).unwrap().lines() {
        let mut v: serde_json::Value = serde_json::from_str(l).unwrap();
        v.as_object_mut().unwrap().remove("rule_hash");
        lines.push(v.to_string());
    }
    std::fs::write(&p, lines.join("\n") + "\n").unwrap();
    assert!(ChainManager::load_from_file(&p, 0).is_err());
}

#[test]
fn rule_hash_round_trips_through_json_and_rvf() {
    let cm = with_rules(3);
    cm.append("s", "k", Some(serde_json::json!({"x": true})));
    let dir = tempfile::tempdir().unwrap();

    let j = dir.path().join("c.jsonl");
    cm.save_to_file(&j).unwrap();
    let from_json = ChainManager::load_from_file(&j, 0).unwrap();

    let r = dir.path().join("c.rvf");
    cm.save_to_rvf(&r).unwrap();
    let from_rvf = ChainManager::load_from_rvf(&r, 0).unwrap();

    for restored in [from_json, from_rvf] {
        assert!(restored.verify_integrity().valid);
        let (a, b) = (cm.tail(0), restored.tail(0));
        assert_eq!(a.len(), b.len());
        for (x, y) in a.iter().zip(&b) {
            assert_eq!(x.rule_hash, y.rule_hash);
            assert_eq!(x.hash, y.hash);
        }
    }
}

#[tokio::test]
async fn append_signed_accepts_a_stamped_event_and_rejects_a_stripped_one() {
    let src = with_rules(4);
    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("c.jsonl");
    src.save_to_file(&p).unwrap();
    let dst = ChainManager::load_from_file(&p, 0).unwrap();

    let ev = src.append("s", "k", None);
    let mut stripped = ev.clone();
    stripped.rule_hash = None;
    assert!(dst.append_signed(stripped).is_err());

    let mut sub = dst.subscribe(ChainFilter::default());
    dst.append_signed(ev.clone()).unwrap();
    match sub.next().await.unwrap() {
        ChainItem::Event(e) => assert_eq!(e.rule_hash, Some([4u8; 32])),
        other => panic!("{other:?}"),
    }
    assert!(dst.verify_integrity().valid);
}

// ---- subscribe ----

async fn collect_until(
    sub: &mut clawft_kernel::chain_subscribe::ChainSubscription,
    last_seq: u64,
) -> Vec<u64> {
    let mut seen = Vec::new();
    while let Some(item) = tokio::time::timeout(Duration::from_secs(10), sub.next())
        .await
        .expect("subscription stalled")
    {
        match item {
            ChainItem::Event(e) => {
                seen.push(e.sequence);
                if e.sequence >= last_seq {
                    break;
                }
            }
            ChainItem::Lagged(n) => panic!("unexpected lag of {n}"),
        }
    }
    seen
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn replay_then_live_has_no_gap_and_no_duplicate_100_iterations() {
    const APPENDS: u64 = 60;
    for iter in 0..100u64 {
        let cm = Arc::new(ChainManager::new(0, 0));
        let writer = {
            let cm = Arc::clone(&cm);
            std::thread::spawn(move || {
                for i in 0..APPENDS {
                    cm.append("w", "race.tick", Some(serde_json::json!({ "i": i })));
                    if i % 7 == 0 {
                        std::thread::yield_now();
                    }
                }
            })
        };
        // Subscribe at a varying point while the writer runs.
        for _ in 0..(iter % 13) {
            tokio::task::yield_now().await;
        }
        let mut sub = cm.subscribe(ChainFilter {
            kind_prefix: None,
            from_seq: Some(0),
        });
        let seen = collect_until(&mut sub, APPENDS).await; // genesis is seq 0
        writer.join().unwrap();
        let expect: Vec<u64> = (0..=APPENDS).collect();
        assert_eq!(seen, expect, "iteration {iter}");
    }
}

#[tokio::test]
async fn kind_prefix_filters_replay_and_live() {
    let cm = ChainManager::new(0, 0);
    cm.append("s", "a.one", None);
    cm.append("s", "b.one", None);
    let mut sub = cm.subscribe(ChainFilter {
        kind_prefix: Some("a.".into()),
        from_seq: Some(0),
    });
    cm.append("s", "b.two", None);
    cm.append("s", "a.two", None);
    let mut kinds = Vec::new();
    for _ in 0..2 {
        match sub.next().await.unwrap() {
            ChainItem::Event(e) => kinds.push(e.kind),
            ChainItem::Lagged(n) => panic!("lag {n}"),
        }
    }
    assert_eq!(kinds, ["a.one", "a.two"]);
}

#[tokio::test]
async fn live_only_skips_history() {
    let cm = ChainManager::new(0, 0);
    cm.append("s", "old", None);
    let mut sub = cm.subscribe(ChainFilter::default());
    cm.append("s", "new", None);
    match sub.next().await.unwrap() {
        ChainItem::Event(e) => assert_eq!(e.kind, "new"),
        other => panic!("{other:?}"),
    }
}

#[tokio::test]
async fn a_stalled_subscriber_never_slows_append_and_sees_lagged() {
    let cm = ChainManager::new(0, 0);
    let mut stalled = cm.subscribe(ChainFilter::default());
    let started = Instant::now();
    for i in 0..5000u64 {
        cm.append("s", "flood", Some(serde_json::json!({ "i": i })));
    }
    assert!(
        started.elapsed() < Duration::from_secs(20),
        "append blocked by a stalled subscriber: {:?}",
        started.elapsed()
    );
    match stalled.next().await.unwrap() {
        ChainItem::Lagged(n) => assert!(n > 0),
        other => panic!("expected Lagged, got {other:?}"),
    }
    // It then recovers and keeps receiving.
    assert!(matches!(stalled.next().await, Some(ChainItem::Event(_))));
}
