"""Two-node placement stage of the Pi lane (card mesh-placement-12).

Both nodes are real, isolated `weaver` daemons, and the Mac side is driven
only through the operator CLI (`weaver workload keygen|pack|explain|place|
status|stop|logs|unload`):

- Pi 5: cross-built weaver, its own HOME, runtime dir and chain under the
  scratch dir, its workload-host served on :9471 with Noise XX (override with
  WEFTOS_PI_PLACEMENT_PORT; the system weaver's mesh port, 9489, and
  ~/.clawft are never touched; a Pi weaver deployed before ADR-103 still
  listens on 9470 until redeployed), policy generated by
  the lane (serve this controller, pin its package key, permit cogs).
- Mac: native weaver in a temp dir (own HOME, runtime dir, node key and
  chain; mesh transport off, so it binds no port and never meets the
  operator's daemon), with the Pi listed as `paired` in workload-peers.json.

The Mac places the released anomaly-detect cog: explain shows why the Pi
wins, the package is fetched from the Mac over the placement connection,
admitted by the Pi daemon's native adapter and run against a synthetic
feed. A package whose `aarch64` binary is really x86-64 is then refused by
the Pi adapter's admission self-check and retried on the next candidate
(the Mac's Docker adapter with `--mac-container`, whose own self-check
refuses it too); pinning the Mac runs the cog in that container, or, without
a container adapter, is refused by the engine (the Mac is never offered a
runtime it has no adapter for). The Pi's paired tier is bound to its node
key once learned. All of it is chained on both daemons. Pure
helpers are in pi_plan (Pi side) and pi_ctl_plan (Mac side).
"""
import json
import os
import shutil
import tempfile
import time

import pi_ctl_plan as ctl
import pi_plan as plan

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
COG_TOML = os.path.join(HERE, "anomaly-detect.cog.toml")
MAC_TARGET = os.environ.get("CARGO_TARGET_DIR") or os.path.join(ROOT, "target")
MAC_WEAVER = os.path.join(MAC_TARGET, "debug", "weaver")
# `daemon-files` (policy-file generator) only; it never places anything.
MAC_NODE_TOOL = os.path.join(MAC_TARGET, "debug", "examples", "workload_node")
RUN_SECS = 8


def pi_binary(target):
    """The cross-built weaver daemon for the Pi."""
    return os.path.join(target, "debug", "weaver")


def build_mac(run):
    """Native builds on the Mac: the weaver controller and the policy tool."""
    print("── Building weaver (Mac controller) and the policy-file tool")
    for args in (plan.weaver_cargo_args(), plan.placement_cargo_args()):
        rc, _ = run(args + ["--manifest-path", os.path.join(ROOT, "Cargo.toml")], capture="quiet")
        if rc != 0:
            raise SystemExit("test-pi: Mac build failed (rc %d)" % rc)


def docker_env(run):
    """(docker CLI dir, DOCKER_HOST of the current context) for the Mac
    daemon's container adapter."""
    cli = shutil.which("docker")
    if not cli:
        raise SystemExit("test-pi: --mac-container needs the docker CLI")
    rc, host = run(["docker", "context", "inspect", "--format", "{{.Endpoints.docker.Host}}"],
                   capture="stdout", timeout=30)
    host = (host or "").strip()
    if run.dry_run:
        host = host or "unix:///var/run/docker.sock"
    if rc != 0 or not host.startswith("unix://"):
        raise SystemExit("test-pi: could not read the docker context endpoint")
    return os.path.dirname(cli), host


def _pid(rc, out, what):
    pid = (out or "").strip().splitlines()[-1:] or ["0"]
    if rc != 0 or not pid[0].isdigit():
        raise SystemExit("test-pi: could not start %s on the Pi" % what)
    return int(pid[0])


class MacController:
    """The isolated Mac weaver daemon and its CLI."""

    def __init__(self, run, work, docker=None):
        self.run, self.work, self.proc, self.docker = run, work, None, docker
        self.containers = []   # instances placed in this Mac's Docker adapter
        for d in ("home", "runtime", "tmp"):
            os.makedirs(os.path.join(work, d), exist_ok=True)
        self.runtime = os.path.join(work, "runtime")

    def cli(self, *argv, timeout=300):
        rc, out = self.run(ctl.env_cmd(self.work, [MAC_WEAVER] + list(argv), self.docker),
                           capture="stdout", timeout=timeout)
        return rc, out or ""

    def json(self, *argv, timeout=300):
        rc, out = self.cli(*argv, timeout=timeout)
        return rc, ctl.load_json(out) or {}

    def start(self):
        cmd = ctl.env_cmd(self.work, [MAC_WEAVER, "kernel", "start", "--foreground"], self.docker)
        self.proc = self.run.spawn(cmd, os.path.join(self.runtime, "mac.log"), self.runtime)

    def wait_ready(self, pi_node, secs=120):
        for _ in range(secs):
            _, st = self.json("workload", "status", "--json", timeout=30)
            me = ctl.mac_ready(st, pi_node)
            if me or self.run.dry_run:
                return me or "n-000000"
            time.sleep(1)
        return None

    def remove_containers(self):
        """Backstop: containers this run placed on the Mac are removed."""
        for iid in self.containers:
            self.run(["docker", "rm", "-f", ctl.container_name(iid)], capture="quiet", timeout=60)
        self.containers = []

    def stop(self):
        if self.proc is not None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=20)
            except Exception:   # still running: SIGKILL
                self.proc.kill()
            self.proc = None


def _keys_and_policy(lane, mac, work):
    """Node key (also the package signer) and both daemons' policy files."""
    hexkey = os.path.join(work, "node.hex")
    rc, out = mac.cli("workload", "keygen", "--out", hexkey)
    pub = ctl.parse_keygen(out) or ("0" * 64 if lane.run.dry_run else None)
    if rc != 0 or not pub:
        raise SystemExit("test-pi: weaver workload keygen failed")
    if not lane.run.dry_run:
        with open(hexkey) as f:
            seed = ctl.seed_bytes(f.read())
        fd = os.open(os.path.join(mac.runtime, "node.key"), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "wb") as f:
            f.write(seed)
    policy = os.path.join(work, "policy")
    rc, _ = lane.run([MAC_NODE_TOOL, "daemon-files", "--controller", pub, "--listen",
                      "0.0.0.0:%d" % plan.PLACEMENT_PORT, "--out", policy], capture="quiet")
    if rc != 0:
        raise SystemExit("test-pi: could not write the daemon policy files")
    if not lane.run.dry_run:
        for f in ("workload-trust.json", "workload-permits.json"):
            shutil.copy(os.path.join(policy, f), mac.runtime)
        write_peers(lane, mac)
        if lane.a.mac_container:
            with open(os.path.join(mac.runtime, "workload-container.json"), "w") as f:
                json.dump(ctl.container_json(lane.a.mac_container), f)
    return hexkey, policy


def write_peers(lane, mac, key=None):
    """The Mac's workload-peers.json (the Pi paired; bound to `key` once known)."""
    peers = ctl.peers_json(plan.ssh_hostname(lane.host), plan.PLACEMENT_PORT, key)
    with open(os.path.join(mac.runtime, "workload-peers.json"), "w") as f:
        json.dump(peers, f)


def pin_pi_key(lane, mac, pi_node):
    """Bind the Pi's paired tier to the key the Mac learned for it (first
    use), then check the daemon still pairs it under that key."""
    _, st = mac.json("workload", "status", "--json", timeout=60)
    key = ctl.pi_key(st, pi_node)
    if lane.run.dry_run:
        return True
    if not key:
        return False
    write_peers(lane, mac, key)
    _, st = mac.json("workload", "status", "--json", timeout=60)
    print("  INFO  the Pi's paired tier is now bound to its node key")
    return ctl.mac_ready(st, pi_node) is not None


def _pack(mac, work, key, name, binary):
    src = os.path.join(work, name + "-src")
    os.makedirs(src, exist_ok=True)
    shutil.copy(COG_TOML, os.path.join(src, "cog.toml"))
    out = os.path.join(work, name)
    rc, _ = mac.cli("workload", "pack", "--cog-dir", src, "--bin", "aarch64=" + binary,
                    "--out", out, "--key", key, "--release-url", ctl.RELEASE_URL)
    if rc != 0:
        raise SystemExit("test-pi: weaver workload pack failed")
    return out


def _drive(mac, work, key, cog_bin, pi_node, mac_node):
    """The CLI session; returns the result dict judged by pi_ctl_plan.judge."""
    pkg = _pack(mac, work, key, "pkg", cog_bin)
    bad_bin = os.path.join(work, "x86_64-labelled-aarch64")
    with open(bad_bin, "wb") as f:
        f.write(ctl.mislabeled_elf())
    bad_pkg = _pack(mac, work, key, "bad-pkg", bad_bin)
    run = ["--mode", "interval", "--interval", "1", "--csi-port", str(plan.PLACEMENT_FEED_PORT),
           "--json"]
    r = {}
    print("── weaver workload explain (Mac daemon)")
    _, r["explain"] = mac.json("workload", "explain", pkg, *run)
    print((r["explain"].get("explain") or "").rstrip())
    print("── weaver workload place")
    r["place_rc"], r["place"] = mac.json("workload", "place", pkg, *run)
    iid = (r["place"].get("placed") or {}).get("instance_id")
    if iid:
        time.sleep(0 if mac.run.dry_run else RUN_SECS)
        _, r["status"] = mac.json("workload", "status", iid, "--json")
        mac.cli("workload", "stop", iid)
        _, logs = mac.cli("workload", "logs", iid)
        r["reports"], r["first_report"] = ctl.count_reports(logs)
        mac.cli("workload", "unload", iid)
        print("  INFO  cog on the Pi: %s, %d report(s)" % (
            (r["status"].get("status") or {}).get("state"), r["reports"]))
    print("── weaver workload place <aarch64 package holding an x86-64 ELF>")
    r["bad_rc"], r["bad"] = mac.json("workload", "place", bad_pkg, *run)
    print((r["bad"].get("explain") or "").rstrip())
    print("── weaver workload place --pin <this Mac>")
    r["pin_rc"], r["pin"] = mac.json("workload", "place", pkg, "--pin", mac_node, *run)
    print((r["pin"].get("explain") or "").rstrip())
    mid = (r["pin"].get("placed") or {}).get("instance_id")
    if mid:   # the Mac's container adapter ran it
        mac.containers.append(mid)
        time.sleep(0 if mac.run.dry_run else RUN_SECS)
        _, r["pin_status"] = mac.json("workload", "status", mid, "--json")
        mac.cli("workload", "stop", mid)
        mac.cli("workload", "unload", mid)
    rc, out = mac.cli("chain", "export", "--format", "json")
    try:
        r["mac_chain"] = json.loads(out) if rc == 0 else None
    except ValueError:
        r["mac_chain"] = None
    return r


def run_placement(lane, cog_bin):
    """Run the stage; appends one result row to lane.results."""
    run, s = lane.run, lane.scratch
    weaver = s + "/bin/weaver"
    work = tempfile.mkdtemp(prefix="wfp-")
    mac = MacController(run, work, docker_env(run) if lane.a.mac_container else None)
    lane.mac_controller = mac
    try:
        if not ctl.socket_fits(work):
            raise SystemExit("test-pi: temp dir path too long for the daemon socket")
        key, policy = _keys_and_policy(lane, mac, work)
        lane.rsync_to([os.path.join(policy, f) for f in
                       ("workload-host.json", "workload-trust.json", "workload-permits.json")],
                      s + "/runtime/")
        print("── Starting an isolated weaver daemon on the Pi (workload-host :%d)"
              % plan.PLACEMENT_PORT)
        rc, out = lane.ssh(plan.weaver_start_command(s, weaver), capture="stdout", timeout=60)
        lane.placement_pid = _pid(rc, out, "weaver")
        rc, out = lane.ssh(plan.feed_start_command(s), capture="stdout", timeout=60)
        lane.feed_pid = _pid(rc, out, "the sensor feed")
        rc, out = lane.ssh(plan.weaver_ready_command(s, weaver), capture="stdout", timeout=200)
        pi_node, served = plan.parse_ready(out)
        if run.dry_run:
            pi_node, served = "n-000000", "0.0.0.0:%d" % plan.PLACEMENT_PORT
        if not pi_node:
            lane.ssh("cat %s/runtime/placement.log | tail -40" % s, timeout=60)
            raise SystemExit("test-pi: the Pi weaver daemon did not serve workload-host")
        print("  INFO  Pi weaver daemon %s serves workload-host on %s" % (pi_node, served))
        print("── Starting an isolated weaver daemon on the Mac (controller)")
        mac.start()
        mac_node = mac.wait_ready(pi_node)
        if not mac_node:
            raise SystemExit("test-pi: the Mac weaver daemon never saw the Pi as a paired target")
        print("  INFO  Mac weaver daemon %s lists the Pi as paired" % mac_node)
        key_pinned = pin_pi_key(lane, mac, pi_node)
        r = _drive(mac, work, key, cog_bin, pi_node, mac_node)
        r["peer_key_pinned"] = key_pinned
        mac.stop()
        rc, out = lane.ssh(plan.weaver_stop_command(s, weaver, lane.placement_pid, lane.feed_pid),
                           capture="stdout", timeout=90)
        lane.placement_pid = lane.feed_pid = None
        log, r["pi_chain"] = plan.split_node_output(out)
        print("── Pi weaver daemon log (tail)\n" + "\n".join(log.strip().splitlines()[-25:]))
        ok, why = ctl.judge(r, pi_node, mac_node, bool(lane.a.mac_container))
        if run.dry_run:
            ok, why = True, []
        for w in why:
            print("  FAIL  placement: " + w)
        lane.results.append(dict(stage="placement", name="mac weaver -> pi5 weaver anomaly-detect",
                                 rc=0 if ok else 1, ok=ok, passed=int(ok), failed=int(not ok),
                                 ignored=0, suites=1))
        print("  %s  placement mac weaver -> pi5 weaver (%d Pi chain events)" % (
            "PASS" if ok else "FAIL", len(r["pi_chain"] or [])))
        if lane.a.placement_evidence and not run.dry_run:
            write_evidence(lane.a.placement_evidence, r, ok, served, pi_node, mac_node,
                           bool(lane.a.mac_container), getattr(lane, "rev", None))
    finally:
        mac.stop()
        mac.remove_containers()
        shutil.rmtree(work, ignore_errors=True)


def write_evidence(path, r, ok, served, pi_node, mac_node, mac_container=False, rev=None):
    """Committed evidence: decisions, explains, attempts and chain kinds only,
    refused if anything address-like or path-like slipped in."""
    pick = lambda d: {k: (d or {}).get(k) for k in ("explain", "attempts", "placed")}
    ev = {
        "card": "mesh-placement-12",
        "ok": ok,
        "source": rev,
        "controller": {"runtime": "weaver daemon (isolated) via `weaver workload` CLI",
                       "node": mac_node,
                       "adapters": ["native", "container (docker)"] if mac_container else ["native"]},
        "pi_peer_bound_to_key": bool(r.get("peer_key_pinned")),
        "pi_node": {"runtime": "weaver daemon (isolated)", "node": pi_node,
                    "workload_host_served_on": served},
        "explain": (r.get("explain") or {}).get("explain"),
        "place": pick(r.get("place")),
        "run": {"state": ((r.get("status") or {}).get("status") or {}).get("state"),
                "reports": r.get("reports"), "first_report": r.get("first_report")},
        "admission_mismatch": pick(r.get("bad")),
        "pin_mac": pick(r.get("pin")),
        "pin_mac_run": ((r.get("pin_status") or {}).get("status") or {}).get("state"),
        "controller_chain": ctl.chain_rows(r.get("mac_chain")),
        "pi_chain": ctl.chain_rows(r.get("pi_chain")),
    }
    text = json.dumps(ev, indent=2) + "\n"
    if plan.LEAK_RE.search(text):
        raise SystemExit("test-pi: placement evidence contains an address or path; not written")
    with open(path, "w") as f:
        f.write(text)
    print("  INFO  placement evidence written")


def cleanup(lane):
    """Backstop: daemons still running (aborted stage) are stopped."""
    mac = getattr(lane, "mac_controller", None)
    if mac is not None:
        mac.stop()
    if getattr(lane, "placement_pid", None) or getattr(lane.a, "placement", False):
        # Stops only processes started from the scratch dir.
        lane.ssh(plan.placement_kill_all_command(lane.a.scratch), capture="quiet", timeout=60)
