//! Agent subsystem: loop, context, memory, skills, agent definitions, sandbox.

pub mod agents;
pub mod context;
pub mod context_compress;
pub mod context_router;
pub mod cost_budget;
pub mod defer;
pub mod effects;
pub mod gate;
pub mod graft;
pub mod helpers;
pub mod hydrate;
pub mod identity;
#[cfg(feature = "native")]
pub mod identity_watcher;
pub mod learning;
pub mod local_file_sink;
pub mod loop_core;
pub mod memory;
pub mod memory_recall;
pub mod runtime;
pub mod sandbox;
pub mod sink;
pub mod skill_autogen;
#[cfg(feature = "native")]
pub mod skill_watcher;
pub mod routing_log;
pub mod soul_journal;
pub mod skills;
pub mod skills_v2;
pub mod spawn;
#[cfg(feature = "native")]
pub mod spawn_context;
pub mod system_prompt;
pub mod tokenizer;
#[cfg(feature = "rvf")]
pub mod turn_checkpoint;
pub mod turn_ledger;
pub mod verification;
